(() => {
"use strict";
const CFG=window.TRADE_TREE_CONFIG||{}, LEAGUE_ID=String(CFG.leagueId||""), MAX_WEEKS=Number(CFG.maxTransactionWeeks||18), CACHE_HOURS=Number(CFG.playerCacheHours||24), API="https://api.sleeper.app/v1";
const state={leagueChain:[],seasons:[],usersByLeague:new Map(),rostersByLeague:new Map(),managerMap:new Map(),trades:[],players:{},currentLeague:null,drafts:[]};
const $=id=>document.getElementById(id), esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
async function api(path){const r=await fetch(`${API}${path}`);if(!r.ok)throw new Error(`Sleeper request failed (${r.status})`);return r.json()}
function toast(m){const e=$("toast");e.textContent=m;e.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("show"),2400)}
function fmtDate(ms){return ms?new Intl.DateTimeFormat(undefined,{month:"short",day:"numeric",year:"numeric"}).format(new Date(Number(ms))):"Unknown date"}
function teamName(lid,rid){const m=state.managerMap.get(`${lid}:${rid}`);return m?.teamName||m?.displayName||`Roster ${rid}`}
function avatarHTML(lid,rid){const m=state.managerMap.get(`${lid}:${rid}`),a=m?.avatar;if(a)return `<img class="avatar" alt="" src="https://sleepercdn.com/avatars/thumbs/${esc(a)}">`;return `<span class="avatar fallback">${esc((teamName(lid,rid)[0]||"T").toUpperCase())}</span>`}
async function loadLeagueChain(){let id=LEAGUE_ID;const seen=new Set();while(id&&id!=="0"&&!seen.has(id)){seen.add(id);const l=await api(`/league/${id}`);state.leagueChain.push(l);id=l.previous_league_id}state.currentLeague=state.leagueChain[0];state.seasons=[...new Set(state.leagueChain.map(l=>String(l.season)))].sort((a,b)=>b-a)}
async function loadPeople(){for(const l of state.leagueChain){const [u,r]=await Promise.all([api(`/league/${l.league_id}/users`),api(`/league/${l.league_id}/rosters`)]);state.usersByLeague.set(String(l.league_id),u);state.rostersByLeague.set(String(l.league_id),r);const um=new Map(u.map(x=>[String(x.user_id),x]));r.forEach(x=>{const z=um.get(String(x.owner_id));state.managerMap.set(`${l.league_id}:${x.roster_id}`,{rosterId:x.roster_id,ownerId:x.owner_id,teamName:z?.metadata?.team_name||z?.display_name||`Roster ${x.roster_id}`,displayName:z?.display_name||"",avatar:z?.avatar||null,roster:x})})}}
async function loadTrades(){const all=[];for(const l of state.leagueChain){const weeks=await Promise.all(Array.from({length:MAX_WEEKS},(_,i)=>api(`/league/${l.league_id}/transactions/${i+1}`).catch(()=>[])));weeks.flat().forEach(tx=>{if(tx?.type==="trade"&&tx?.status==="complete")all.push({...tx,_leagueId:String(l.league_id),_season:String(l.season)})})}const d=new Map();all.forEach(t=>d.set(String(t.transaction_id),t));state.trades=[...d.values()].sort((a,b)=>Number(b.created||0)-Number(a.created||0))}
async function loadPlayers(){const key="allBeef.players.v2";try{const c=JSON.parse(localStorage.getItem(key)||"null");if(c&&Date.now()-c.savedAt<CACHE_HOURS*3600000&&c.players){state.players=c.players;return}}catch(_){}try{state.players=await api("/players/nfl");try{localStorage.setItem(key,JSON.stringify({savedAt:Date.now(),players:state.players}))}catch(_){}}catch(_){state.players={}}}
function playerName(id){const p=state.players[String(id)];return p?.full_name||[p?.first_name,p?.last_name].filter(Boolean).join(" ")||`Player ${id}`}
function pickKey(p){return `pick:${p.season}:${p.round}:${p.roster_id}`}
function pickLabel(p,lid){const ord={1:"1st",2:"2nd",3:"3rd"}[Number(p.round)]||`${p.round}th`;return `${p.season} ${ord} (${teamName(lid,p.roster_id)})`}
function allAssets(tx){const out=[],adds=tx.adds||{},drops=tx.drops||{};new Set([...Object.keys(adds),...Object.keys(drops)]).forEach(pid=>out.push({key:`player:${pid}`,type:"player",label:playerName(pid),from:drops[pid]??null,to:adds[pid]??null}));(tx.draft_picks||[]).forEach(p=>out.push({key:pickKey(p),type:"pick",label:pickLabel(p,tx._leagueId),from:p.previous_owner_id??null,to:p.owner_id??null}));(tx.waiver_budget||[]).forEach((w,i)=>out.push({key:`faab:${tx.transaction_id}:${i}`,type:"faab",label:`$${w.amount} FAAB`,from:w.sender,to:w.receiver}));return out}
const assetsReceived=(tx,rid)=>allAssets(tx).filter(a=>Number(a.to)===Number(rid)), assetsSent=(tx,rid)=>allAssets(tx).filter(a=>Number(a.from)===Number(rid));
function currentRosterIds(){return(state.rostersByLeague.get(String(state.currentLeague.league_id))||[]).map(r=>r.roster_id)}
function currentManagerForRoster(rid){return state.managerMap.get(`${state.currentLeague.league_id}:${rid}`)}
function resolveHistoricRosterForCurrent(rid,tx){if((tx.roster_ids||[]).some(x=>Number(x)===Number(rid)))return Number(rid);const c=currentManagerForRoster(rid);const h=(state.rostersByLeague.get(String(tx._leagueId))||[]).find(r=>String(r.owner_id)===String(c?.ownerId));return h?.roster_id??Number(rid)}
function tradesForCurrentRoster(rid){return state.trades.filter(tx=>(tx.roster_ids||[]).some(x=>Number(x)===Number(resolveHistoricRosterForCurrent(rid,tx))))}
function chipHTML(a){return `<span class="chip ${a.type==="pick"?"pick":""}">${esc(a.label)}</span>`}
function tradeCardHTML(tx){const sides=(tx.roster_ids||[]).map(rid=>`<div class="trade-side"><div class="team-line">${avatarHTML(tx._leagueId,rid)}<span>${esc(teamName(tx._leagueId,rid))}</span></div><div class="received">${assetsReceived(tx,rid).map(chipHTML).join("")||'<span class="muted">No mapped assets</span>'}</div></div>`).join("");return `<article class="trade-card"><div class="trade-head"><strong>${esc(tx._season)} · Week ${esc(tx.leg??"—")}</strong><span>${esc(fmtDate(tx.created))}</span></div><div class="trade-sides">${sides}</div></article>`}
function renderTrades(){const season=$("seasonFilter").value,q=$("tradeSearch").value.trim().toLowerCase();const f=state.trades.filter(tx=>(season==="all"||tx._season===season)&&(!q||[...(tx.roster_ids||[]).map(r=>teamName(tx._leagueId,r)),...allAssets(tx).map(a=>a.label),tx._season].join(" ").toLowerCase().includes(q)));$("tradeResultCount").textContent=f.length;$("tradeList").innerHTML=f.length?f.map(tradeCardHTML).join(""):'<div class="card empty">No trades match those filters.</div>'}
function renderTeams(){const lid=String(state.currentLeague.league_id);$("teamsGrid").innerHTML=currentRosterIds().map(rid=>{const m=state.managerMap.get(`${lid}:${rid}`),n=tradesForCurrentRoster(rid).length;return `<article class="card team-card"><div class="team-line">${avatarHTML(lid,rid)}<div><strong>${esc(m?.teamName)}</strong><p>${esc(m?.displayName)}</p></div></div><div class="team-stats"><div><strong>${m?.roster?.settings?.wins??0}-${m?.roster?.settings?.losses??0}</strong><span>record</span></div><div><strong>${n}</strong><span>trades</span></div><div><strong>${(m?.roster?.players||[]).length}</strong><span>players</span></div></div></article>`}).join("")}
function renderHome(){const ids=currentRosterIds(),active=ids.map(r=>({rid:r,n:tradesForCurrentRoster(r).length})).sort((a,b)=>b.n-a.n);$("homeStats").innerHTML=[["Seasons",state.seasons.length],["Completed trades",state.trades.length],["Franchises",ids.length],["Tree-ready assets",state.trades.reduce((n,t)=>n+allAssets(t).length,0)]].map(x=>`<div class="summary-card"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join("");$("recentTrades").innerHTML=state.trades.slice(0,5).map(t=>`<div class="compact-row"><div><strong>${esc((t.roster_ids||[]).map(r=>teamName(t._leagueId,r)).join(" ↔ "))}</strong><br><small>${esc(fmtDate(t.created))}</small></div><small>${esc(t._season)}</small></div>`).join("")||'<div class="empty">No trades yet.</div>';$("activeTeams").innerHTML=active.slice(0,5).map((x,i)=>`<div class="compact-row"><div class="rank-left"><span class="rank-num">${i+1}</span>${avatarHTML(String(state.currentLeague.league_id),x.rid)}<strong>${esc(teamName(String(state.currentLeague.league_id),x.rid))}</strong></div><small>${x.n} trades</small></div>`).join("")}
async function renderTrending(){for(const [type,id] of [["add","trendingAdds"],["drop","trendingDrops"]]){try{const rows=await api(`/players/nfl/trending/${type}?lookback_hours=24&limit=25`);$(id).innerHTML=rows.map((x,i)=>`<div class="rank-row"><div class="rank-left"><span class="rank-num">${i+1}</span><div><strong>${esc(playerName(x.player_id))}</strong><br><small>${esc(state.players[String(x.player_id)]?.position||"NFL")}</small></div></div><strong>${x.count}</strong></div>`).join("")}catch(_){$(id).innerHTML='<div class="empty">Trending data unavailable.</div>'}}}
async function loadDrafts(){const seen=new Set(),out=[];for(const l of state.leagueChain){try{const ds=await api(`/league/${l.league_id}/drafts`);for(const d of ds){if(seen.has(d.draft_id))continue;seen.add(d.draft_id);let picks=[];try{picks=await api(`/draft/${d.draft_id}/picks`)}catch(_){}out.push({draft:d,picks,season:l.season,leagueId:String(l.league_id)})}}catch(_){}}state.drafts=out.sort((a,b)=>Number(b.season)-Number(a.season))}
function renderDrafts(){$("draftCountBadge").textContent=`${state.drafts.length} drafts`;$("draftsList").innerHTML=state.drafts.length?state.drafts.map(x=>`<article class="draft-card"><div class="section-title-row"><div><p class="eyebrow">${esc(x.season)}</p><h3>${esc(x.draft.metadata?.name||x.draft.type||"Rookie Draft")}</h3></div><span class="badge">${x.picks.length} picks</span></div><div class="draft-picks">${x.picks.slice(0,36).map(p=>`<div class="draft-pick"><strong>${esc(p.pick_no)}. ${esc(p.metadata?.first_name&&p.metadata?.last_name?`${p.metadata.first_name} ${p.metadata.last_name}`:playerName(p.player_id))}</strong><span>${esc(teamName(x.leagueId,p.roster_id))}</span></div>`).join("")}</div></article>`).join(""):'<div class="card empty">No draft history found.</div>'}
function populateControls(){$("treeTeamSelect").innerHTML=currentRosterIds().map(r=>`<option value="${r}">${esc(teamName(String(state.currentLeague.league_id),r))}</option>`).join("");$("seasonFilter").innerHTML='<option value="all">All seasons</option>'+state.seasons.map(s=>`<option value="${s}">${s}</option>`).join("");populateRootTrades()}
function populateRootTrades(){const rid=Number($("treeTeamSelect").value),ts=tradesForCurrentRoster(rid);$("rootTradeSelect").innerHTML=ts.map(t=>{const h=resolveHistoricRosterForCurrent(rid,t),rec=assetsReceived(t,h).map(a=>a.label).slice(0,2).join(", ");return `<option value="${t.transaction_id}">${esc(t._season)} · ${esc(fmtDate(t.created))} · ${esc(rec||"Trade")}</option>`}).join("");renderTree()}
function findNextSpend(key,after,rid){for(const tx of [...state.trades].sort((a,b)=>Number(a.created)-Number(b.created))){if(Number(tx.created)<=Number(after))continue;const h=resolveHistoricRosterForCurrent(rid,tx);if(assetsSent(tx,h).some(a=>a.key===key))return{tx,rid:h}}return null}
function traceAsset(a,root,rid,d=0,v=new Set()){const k=`${a.key}:${root.transaction_id}`;if(v.has(k)||d>8)return null;v.add(k);const s=findNextSpend(a.key,root.created,rid);if(!s)return{asset:a,status:"held",depth:d,children:[]};return{asset:a,status:"spent",depth:d,spentTx:s.tx,children:assetsReceived(s.tx,s.rid).map(x=>traceAsset(x,s.tx,rid,d+1,new Set(v))).filter(Boolean)}}
function countNodes(n){return 1+(n.children||[]).reduce((a,c)=>a+countNodes(c),0)}function maxDepth(n){return Math.max(n.depth,...(n.children||[]).map(maxDepth))}
function nodeHTML(n){return `<div class="tree-level"><div class="tree-trade"><strong>${n.status==="held"?"Still held":"Moved again"}</strong><div class="tree-meta">${n.spentTx?`${esc(n.spentTx._season)} · ${esc(fmtDate(n.spentTx.created))}`:"Current branch endpoint"}</div></div><div class="tree-assets"><div class="asset ${n.status==="held"?"live":"spent"}"><span class="asset-type">${esc(n.asset.type)}</span><strong>${esc(n.asset.label)}</strong><small>${n.status==="held"?"Branch remains open":"Traded away"}</small>${n.children?.length?`<div class="tree-return">Became ${n.children.length} asset${n.children.length===1?"":"s"}</div>`:""}</div>${(n.children||[]).map(nodeHTML).join("")}</div></div>`}
function renderTree(){const rid=Number($("treeTeamSelect").value),tx=state.trades.find(t=>String(t.transaction_id)===String($("rootTradeSelect").value));if(!tx){$("treeCanvas").innerHTML='<div class="empty">No trade selected.</div>';return}const h=resolveHistoricRosterForCurrent(rid,tx),roots=assetsReceived(tx,h).map(a=>traceAsset(a,tx,rid)).filter(Boolean),nodes=roots.reduce((a,n)=>a+countNodes(n),0),open=roots.reduce((a,n)=>a+(JSON.stringify(n).match(/"status":"held"/g)||[]).length,0),depth=roots.length?Math.max(...roots.map(maxDepth)):0;$("branchCount").textContent=roots.length;$("treeTitle").textContent=`${teamName(tx._leagueId,h)} trade tree`;$("treeDate").textContent=fmtDate(tx.created);$("treeSummary").innerHTML=[["Starting assets",roots.length],["Total nodes",nodes],["Open endpoints",open]].map(x=>`<div class="summary-card"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join("");$("treeCanvas").innerHTML=roots.length?roots.map(nodeHTML).join(""):'<div class="empty">No received assets could be mapped for this trade.</div>'}
function nav(view){document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===`view-${view}`));document.querySelectorAll(".tab").forEach(t=>t.classList.toggle("active",t.dataset.view===view));window.scrollTo({top:0,behavior:"smooth"})}
function bind(){document.querySelectorAll("[data-view]").forEach(x=>x.addEventListener("click",()=>nav(x.dataset.view)));document.querySelectorAll("[data-nav]").forEach(x=>x.addEventListener("click",()=>nav(x.dataset.nav)));$("refreshBtn").addEventListener("click",()=>location.reload());$("tradeSearch").addEventListener("input",renderTrades);$("seasonFilter").addEventListener("change",renderTrades);$("treeTeamSelect").addEventListener("change",populateRootTrades);$("rootTradeSelect").addEventListener("change",renderTree)}
async function init(){try{$("leagueIdLabel").textContent=LEAGUE_ID;$("footerLeague").textContent=LEAGUE_ID;await loadLeagueChain();$("leagueName").textContent=state.currentLeague.name||"All-Beef Dynasty";await Promise.all([loadPeople(),loadTrades(),loadPlayers()]);await loadDrafts();populateControls();renderHome();renderTrades();renderTeams();renderDrafts();renderTrending();$("tradesBadge").textContent=`${state.trades.length} trades`;$("teamsBadge").textContent=`${currentRosterIds().length} teams`;$("syncText").textContent=`Synced · ${state.currentLeague.season}`;bind()}catch(e){console.error(e);$("syncText").textContent="Sync failed";toast(e.message||"Unable to load league")}}
init();
})();