(() => {
"use strict";
const CFG=window.TRADE_TREE_CONFIG||{}, LEAGUE_ID=String(CFG.leagueId||""), MAX_WEEKS=Number(CFG.maxTransactionWeeks||18), CACHE_HOURS=Number(CFG.playerCacheHours||24);
const API="https://api.sleeper.app/v1", DATA_API="https://api.sleeper.com";
const state={leagueChain:[],seasons:[],usersByLeague:new Map(),rostersByLeague:new Map(),managerMap:new Map(),trades:[],players:{},currentLeague:null,drafts:[],tradedPicks:[],matchups:new Map(),seasonStats:new Map(),projections:{},analytics:[],tradeGrades:new Map(),draftGrades:[],managerGrades:[],dataStatus:{stats:false,projections:false}};
const $=id=>document.getElementById(id), esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n)), avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0, sum=a=>a.reduce((x,y)=>x+y,0);
async function api(path){const r=await fetch(`${API}${path}`);if(!r.ok)throw new Error(`Sleeper request failed (${r.status})`);return r.json()}
async function fetchJSON(url){const r=await fetch(url);if(!r.ok)throw new Error(`${r.status}`);return r.json()}
function toast(m){const e=$("toast");e.textContent=m;e.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("show"),2400)}
function fmtDate(ms){return ms?new Intl.DateTimeFormat(undefined,{month:"short",day:"numeric",year:"numeric"}).format(new Date(Number(ms))):"Unknown date"}
function teamName(lid,rid){const m=state.managerMap.get(`${lid}:${rid}`);return m?.teamName||m?.displayName||`Roster ${rid}`}
function avatarHTML(lid,rid){const m=state.managerMap.get(`${lid}:${rid}`),a=m?.avatar;if(a)return `<img class="avatar" alt="" src="https://sleepercdn.com/avatars/thumbs/${esc(a)}">`;return `<span class="avatar fallback">${esc((teamName(lid,rid)[0]||"T").toUpperCase())}</span>`}
function grade(score){return score>=93?"A+":score>=90?"A":score>=87?"A-":score>=83?"B+":score>=80?"B":score>=77?"B-":score>=73?"C+":score>=70?"C":score>=67?"C-":score>=63?"D+":score>=60?"D":"F"}
function gradeClass(g){return g.startsWith("A")?"grade-a":g.startsWith("B")?"grade-b":g.startsWith("C")?"grade-c":g.startsWith("D")?"grade-d":"grade-f"}
function norm(items,key){const vals=items.map(x=>Number(x[key]||0)),lo=Math.min(...vals),hi=Math.max(...vals);items.forEach(x=>x[`${key}N`]=hi===lo?75:50+50*(Number(x[key]||0)-lo)/(hi-lo))}
function percentile(values,v){if(!values.length)return 50;return 100*values.filter(x=>x<=v).length/values.length}

async function loadLeagueChain(){let id=LEAGUE_ID;const seen=new Set();while(id&&id!=="0"&&!seen.has(id)){seen.add(id);const l=await api(`/league/${id}`);state.leagueChain.push(l);id=l.previous_league_id}state.currentLeague=state.leagueChain[0];state.seasons=[...new Set(state.leagueChain.map(l=>String(l.season)))].sort((a,b)=>b-a)}
async function loadPeople(){for(const l of state.leagueChain){const [u,r]=await Promise.all([api(`/league/${l.league_id}/users`),api(`/league/${l.league_id}/rosters`)]);state.usersByLeague.set(String(l.league_id),u);state.rostersByLeague.set(String(l.league_id),r);const um=new Map(u.map(x=>[String(x.user_id),x]));r.forEach(x=>{const z=um.get(String(x.owner_id));state.managerMap.set(`${l.league_id}:${x.roster_id}`,{rosterId:x.roster_id,ownerId:x.owner_id,teamName:z?.metadata?.team_name||z?.display_name||`Roster ${x.roster_id}`,displayName:z?.display_name||"",avatar:z?.avatar||null,roster:x})})}}
async function loadTrades(){const all=[];for(const l of state.leagueChain){const weeks=await Promise.all(Array.from({length:MAX_WEEKS},(_,i)=>api(`/league/${l.league_id}/transactions/${i+1}`).catch(()=>[])));weeks.flat().forEach(tx=>{if(tx?.type==="trade"&&tx?.status==="complete")all.push({...tx,_leagueId:String(l.league_id),_season:String(l.season)})})}const d=new Map();all.forEach(t=>d.set(String(t.transaction_id),t));state.trades=[...d.values()].sort((a,b)=>Number(b.created||0)-Number(a.created||0))}
async function loadPlayers(){const key="allBeef.players.v3";try{const c=JSON.parse(localStorage.getItem(key)||"null");if(c&&Date.now()-c.savedAt<CACHE_HOURS*3600000&&c.players){state.players=c.players;return}}catch(_){}state.players=await api("/players/nfl");try{localStorage.setItem(key,JSON.stringify({savedAt:Date.now(),players:state.players}))}catch(_){}}
function playerName(id){const p=state.players[String(id)];return p?.full_name||[p?.first_name,p?.last_name].filter(Boolean).join(" ")||`Player ${id}`}
function playerPos(id){return state.players[String(id)]?.position||"—"}
function playerAge(id,season=Number(state.currentLeague?.season||2026)){const p=state.players[String(id)];if(p?.age)return Number(p.age);if(p?.birth_date){const y=Number(String(p.birth_date).slice(0,4));if(y)return season-y}return 27}
function normalizeFootballRows(raw){if(Array.isArray(raw)){const m={};raw.forEach(x=>{const id=String(x.player_id||x.player?.player_id||"");if(id)m[id]=x.stats||x});return m}if(raw&&typeof raw==="object"){const m={};for(const [k,v] of Object.entries(raw)){if(v&&typeof v==="object"){const id=String(v.player_id||v.player?.player_id||k);m[id]=v.stats||v}}return m}return{}}
async function footballData(kind,season){const urls=[`${DATA_API}/${kind}/nfl/${season}?season_type=regular`,`${API}/${kind}/nfl/regular/${season}`];for(const u of urls){try{return normalizeFootballRows(await fetchJSON(u))}catch(_){}}return{}}
async function loadNFLData(){const current=Number(state.currentLeague.season),years=[...new Set(state.leagueChain.map(l=>Number(l.season)-1).filter(y=>y>2018))];const stats=await Promise.all(years.map(async y=>[y,await footballData("stats",y)]));stats.forEach(([y,d])=>state.seasonStats.set(y,d));state.dataStatus.stats=stats.some(([,d])=>Object.keys(d).length);state.projections=await footballData("projections",current);state.dataStatus.projections=Object.keys(state.projections).length}
async function loadCurrentExtras(){const lid=String(state.currentLeague.league_id);state.tradedPicks=await api(`/league/${lid}/traded_picks`).catch(()=>[]);for(const l of state.leagueChain){const weeks=[];for(let w=1;w<=MAX_WEEKS;w++)weeks.push(api(`/league/${l.league_id}/matchups/${w}`).catch(()=>[]));state.matchups.set(String(l.league_id),(await Promise.all(weeks)).flat())}}
async function loadDrafts(){const seen=new Set(),out=[];for(const l of state.leagueChain){try{const ds=await api(`/league/${l.league_id}/drafts`);for(const d of ds){if(seen.has(d.draft_id))continue;seen.add(d.draft_id);let picks=[];try{picks=await api(`/draft/${d.draft_id}/picks`)}catch(_){}out.push({draft:d,picks,season:l.season,leagueId:String(l.league_id)})}}catch(_){}}state.drafts=out.sort((a,b)=>Number(b.season)-Number(a.season))}

function scoreRaw(stats){if(!stats)return 0;const scoring=state.currentLeague.scoring_settings||{};let total=0,used=0;for(const [k,w] of Object.entries(scoring)){if(Number.isFinite(Number(stats[k]))){total+=Number(stats[k])*Number(w);used++}}if(used)return total;return Number(stats.pts_half_ppr??stats.pts_ppr??stats.pts_std??0)}
function seasonPoints(pid,season){return scoreRaw(state.seasonStats.get(Number(season))?.[String(pid)])}
function projectedPoints(pid){return scoreRaw(state.projections[String(pid)])}
function ageFactor(pid,season=Number(state.currentLeague.season)){const age=playerAge(pid,season),pos=playerPos(pid);const peak=pos==="RB"?24.5:pos==="WR"?26:pos==="TE"?27:pos==="QB"?29:26;return clamp(100-Math.abs(age-peak)*7,35,100)}
function playerValue(pid,season=Number(state.currentLeague.season)){const p=state.players[String(pid)];if(!p)return 0;const prev=seasonPoints(pid,season-1),proj=season===Number(state.currentLeague.season)?projectedPoints(pid):0;const production=Math.max(prev,proj*.92);const pos=p.position;const scarcity=pos==="QB"?0.82:pos==="TE"?1.04:pos==="RB"?1.06:pos==="WR"?1:0.45;const active=p.active===false?0.35:1;return Math.max(0,(production*.68+ageFactor(pid,season)*1.1)*scarcity*active)}
function pickValue(round,yearsAway=1){const base={1:265,2:135,3:72,4:38,5:20}[Number(round)]||15;return base*Math.pow(.90,Math.max(0,yearsAway-1))}
function pickKey(p){return `pick:${p.season}:${p.round}:${p.roster_id}`}
function pickLabel(p,lid){const ord={1:"1st",2:"2nd",3:"3rd"}[Number(p.round)]||`${p.round}th`;return `${p.season} ${ord} (${teamName(lid,p.roster_id)})`}
function allAssets(tx){const out=[],adds=tx.adds||{},drops=tx.drops||{};new Set([...Object.keys(adds),...Object.keys(drops)]).forEach(pid=>out.push({key:`player:${pid}`,type:"player",label:playerName(pid),pid:String(pid),from:drops[pid]??null,to:adds[pid]??null}));(tx.draft_picks||[]).forEach(p=>out.push({key:pickKey(p),type:"pick",label:pickLabel(p,tx._leagueId),pick:p,from:p.previous_owner_id??null,to:p.owner_id??null}));(tx.waiver_budget||[]).forEach((w,i)=>out.push({key:`faab:${tx.transaction_id}:${i}`,type:"faab",label:`$${w.amount} FAAB`,amount:Number(w.amount||0),from:w.sender,to:w.receiver}));return out}
const assetsReceived=(tx,rid)=>allAssets(tx).filter(a=>Number(a.to)===Number(rid)), assetsSent=(tx,rid)=>allAssets(tx).filter(a=>Number(a.from)===Number(rid));
function assetValue(a,season=Number(state.currentLeague.season)){if(a.type==="player")return playerValue(a.pid,season);if(a.type==="pick"){const away=Math.max(1,Number(a.pick.season)-season);return pickValue(a.pick.round,away)}if(a.type==="faab")return a.amount*.65;return 0}
function currentRosterIds(){return(state.rostersByLeague.get(String(state.currentLeague.league_id))||[]).map(r=>r.roster_id)}
function currentManagerForRoster(rid){return state.managerMap.get(`${state.currentLeague.league_id}:${rid}`)}
function resolveHistoricRosterForCurrent(rid,tx){if((tx.roster_ids||[]).some(x=>Number(x)===Number(rid)))return Number(rid);const c=currentManagerForRoster(rid);const h=(state.rostersByLeague.get(String(tx._leagueId))||[]).find(r=>String(r.owner_id)===String(c?.ownerId));return h?.roster_id??Number(rid)}
function tradesForCurrentRoster(rid){return state.trades.filter(tx=>(tx.roster_ids||[]).some(x=>Number(x)===Number(resolveHistoricRosterForCurrent(rid,tx))))}
function lifetimeForRoster(rid){const owner=currentManagerForRoster(rid)?.ownerId;let wins=0,losses=0,ties=0,points=0,seasons=0;for(const l of state.leagueChain){const r=(state.rostersByLeague.get(String(l.league_id))||[]).find(x=>String(x.owner_id)===String(owner));if(!r)continue;wins+=Number(r.settings?.wins||0);losses+=Number(r.settings?.losses||0);ties+=Number(r.settings?.ties||0);const ms=(state.matchups.get(String(l.league_id))||[]).filter(m=>Number(m.roster_id)===Number(r.roster_id));points+=sum(ms.map(m=>Number(m.points||0)));seasons++}return{wins,losses,ties,points,seasons,pct:(wins+losses+ties)?(wins+.5*ties)/(wins+losses+ties):.5}}
function rosterPickCapital(rid){const season=Number(state.currentLeague.season),rounds=Number(state.currentLeague.settings?.draft_rounds||4);let total=0;for(let y=season+1;y<=season+3;y++)for(let r=1;r<=rounds;r++){let owner=rid;const moved=state.tradedPicks.find(p=>Number(p.season)===y&&Number(p.round)===r&&Number(p.roster_id)===Number(rid));if(moved)owner=Number(moved.owner_id);if(Number(owner)===Number(rid))total+=pickValue(r,y-season)}for(const p of state.tradedPicks){if(Number(p.owner_id)===Number(rid)&&Number(p.roster_id)!==Number(rid)&&Number(p.season)>season&&Number(p.season)<=season+3)total+=pickValue(p.round,Number(p.season)-season)}return total}
function chooseLineup(players){const ids=[...players],slots=(state.currentLeague.roster_positions||[]).filter(s=>!["BN","IR","TAXI"].includes(s)),used=new Set(),chosen=[];const eligible=(pid,slot)=>{const p=playerPos(pid);if(slot==="FLEX")return["RB","WR","TE"].includes(p);if(slot==="WRRB_FLEX")return["RB","WR"].includes(p);if(slot==="REC_FLEX")return["WR","TE"].includes(p);if(slot==="SUPER_FLEX")return["QB","RB","WR","TE"].includes(p);return p===slot};for(const slot of slots){const opts=ids.filter(pid=>!used.has(pid)&&eligible(pid,slot)).sort((a,b)=>playerValue(b)-playerValue(a));if(opts[0]){used.add(opts[0]);chosen.push(opts[0])}}return{chosen,bench:ids.filter(x=>!used.has(x))}}
function buildAnalytics(){const lid=String(state.currentLeague.league_id),rows=currentRosterIds().map(rid=>{const m=state.managerMap.get(`${lid}:${rid}`),players=(m?.roster?.players||[]).filter(pid=>state.players[String(pid)]),lu=chooseLineup(players);const lineup=sum(lu.chosen.map(pid=>playerValue(pid))),depth=sum(lu.bench.sort((a,b)=>playerValue(b)-playerValue(a)).slice(0,8).map(pid=>playerValue(pid))),dynasty=sum(players.sort((a,b)=>playerValue(b)-playerValue(a)).slice(0,18).map(pid=>playerValue(pid))),production=sum(lu.chosen.map(pid=>Math.max(seasonPoints(pid,Number(state.currentLeague.season)-1),projectedPoints(pid)*.9))),capital=rosterPickCapital(rid),ages=players.filter(pid=>["QB","RB","WR","TE"].includes(playerPos(pid))).sort((a,b)=>playerValue(b)-playerValue(a)).slice(0,12).map(pid=>playerAge(pid)),avgAge=avg(ages),youth=clamp(105-(avgAge-23)*8),life=lifetimeForRoster(rid);return{rid,name:teamName(lid,rid),lineup,depth,dynasty,production,capital,avgAge,youth,life,players}});["lineup","depth","dynasty","production","capital"].forEach(k=>norm(rows,k));rows.forEach(x=>{x.power=clamp(.35*x.lineupN+.20*x.depthN+.20*x.dynastyN+.15*x.productionN+.10*x.capitalN);x.tier=x.power>=90?"Elite":x.power>=82?"Contender":x.power>=72?"Hopeful":x.power>=62?"Retool":"Rebuild"});rows.sort((a,b)=>b.power-a.power);rows.forEach((x,i)=>x.rank=i+1);state.analytics=rows}

function buildTradeGrades(){state.tradeGrades.clear();for(const tx of state.trades){const season=Number(tx._season),sides=(tx.roster_ids||[]).map(rid=>{const assets=assetsReceived(tx,rid),value=sum(assets.map(a=>assetValue(a,season))),count=assets.length;return{rid:Number(rid),assets,value,count}});const values=sides.map(s=>s.value),mean=avg(values),spread=Math.max(20,mean*.20);sides.forEach(s=>{const rel=mean?50+35*(s.value-mean)/spread:75;const completeness=s.count?8:0;const score=clamp(70+clamp(rel-50,-20,20)+completeness);s.score=score;s.grade=grade(score);s.reason=s.value>mean*1.12?"Acquired the strongest modeled asset package.":s.value<mean*.88?"Received less modeled value than the other side.":"Modeled value was close to the trade average."});state.tradeGrades.set(String(tx.transaction_id),sides)}}
function buildDraftGrades(){const all=[];for(const d of state.drafts){if(!d.picks.length)continue;const values=d.picks.map(p=>playerValue(p.player_id,Number(state.currentLeague.season))),maxPick=Math.max(...d.picks.map(p=>Number(p.pick_no||1)));const team=new Map();d.picks.forEach((p,i)=>{const v=values[i],classPct=percentile(values,v),costPct=100*(1-(Number(p.pick_no||i+1)-1)/Math.max(1,maxPick-1)),score=clamp(55+.55*classPct-.25*costPct),g=grade(score),r=Number(p.roster_id);if(!team.has(r))team.set(r,[]);team.get(r).push({p,score,g,v})});for(const [rid,picks] of team){const score=avg(picks.map(x=>x.score));all.push({draft:d,rid,score,grade:grade(score),picks})}}state.draftGrades=all}
function buildManagerGrades(){const rows=state.analytics.map(a=>{const trades=tradesForCurrentRoster(a.rid),tradeScores=[];trades.forEach(tx=>{const hr=resolveHistoricRosterForCurrent(a.rid,tx),g=(state.tradeGrades.get(String(tx.transaction_id))||[]).find(x=>Number(x.rid)===Number(hr));if(g)tradeScores.push(g.score)});const owner=currentManagerForRoster(a.rid)?.ownerId,dgs=state.draftGrades.filter(d=>{const hist=(state.rostersByLeague.get(String(d.draft.leagueId))||[]).find(r=>String(r.owner_id)===String(owner));return hist&&Number(hist.roster_id)===Number(d.rid)});const tradeScore=tradeScores.length?avg(tradeScores):72,draftScore=dgs.length?avg(dgs.map(x=>x.score)):72,results=clamp(55+a.life.pct*45),activity=clamp(55+Math.min(35,trades.length*2)+a.capitalN*.1),score=clamp(.30*a.power+.25*tradeScore+.20*draftScore+.15*results+.10*activity);return{...a,tradeScore,draftScore,results,activity,gmScore:score,gmGrade:grade(score),tradeCount:trades.length,draftCount:dgs.length}}).sort((a,b)=>b.gmScore-a.gmScore);rows.forEach((x,i)=>x.gmRank=i+1);state.managerGrades=rows}
function insight(m){const strengths=[["lineup",m.lineupN],["depth",m.depthN],["dynasty core",m.dynastyN],["draft capital",m.capitalN],["trade record",m.tradeScore],["draft record",m.draftScore]].sort((a,b)=>b[1]-a[1]),weak=[...strengths].sort((a,b)=>a[1]-b[1]);return `Best edge: ${strengths[0][0]} (${Math.round(strengths[0][1])}). Biggest opportunity: ${weak[0][0]} (${Math.round(weak[0][1])}).`}

function chipHTML(a){return `<span class="chip ${a.type==="pick"?"pick":""}">${esc(a.label)}</span>`}
function tradeCardHTML(tx){const grades=state.tradeGrades.get(String(tx.transaction_id))||[];const sides=(tx.roster_ids||[]).map(rid=>{const g=grades.find(x=>Number(x.rid)===Number(rid)),assets=assetsReceived(tx,rid);return `<div class="trade-side"><div class="trade-grade-side"><div class="team-line">${avatarHTML(tx._leagueId,rid)}<span>${esc(teamName(tx._leagueId,rid))}</span></div>${g?`<span class="grade-pill ${gradeClass(g.grade)}">${g.grade}</span>`:""}</div><div class="received">${assets.map(chipHTML).join("")||'<span class="muted">No mapped assets</span>'}</div>${g?`<div class="value-line">Modeled package value: ${Math.round(g.value)}</div><div class="grade-reason">${esc(g.reason)}</div>`:""}</div>`}).join("");return `<article class="trade-card graded-card"><div class="trade-head"><strong>${esc(tx._season)} · Week ${esc(tx.leg??"—")}</strong><span>${esc(fmtDate(tx.created))}</span></div><div class="trade-sides">${sides}</div></article>`}
function renderTrades(){const season=$("seasonFilter").value,q=$("tradeSearch").value.trim().toLowerCase();const f=state.trades.filter(tx=>(season==="all"||tx._season===season)&&(!q||[...(tx.roster_ids||[]).map(r=>teamName(tx._leagueId,r)),...allAssets(tx).map(a=>a.label),tx._season].join(" ").toLowerCase().includes(q)));$("tradeResultCount").textContent=f.length;$("tradeList").innerHTML=f.length?f.map(tradeCardHTML).join(""):'<div class="card empty">No trades match those filters.</div>'}
function tierClass(t){return t==="Elite"?"elite":t==="Contender"?"contender":t==="Hopeful"?"hopeful":t==="Retool"?"retool":"rebuild"}
function renderPower(){const lid=String(state.currentLeague.league_id);$("powerDataBadge").innerHTML=`<span class="data-quality">${state.dataStatus.projections?"2026 projections":"prior production"} + NFL stats</span>`;$("powerRankings").innerHTML=state.analytics.map(a=>`<article class="power-row rank-${a.rank<=3?a.rank:"other"}"><div class="power-rank">#${a.rank}</div><div class="power-team">${avatarHTML(lid,a.rid)}<div><strong>${esc(a.name)}</strong><small>${a.life.wins}-${a.life.losses} historical record</small><span class="tier ${tierClass(a.tier)}">${a.tier}</span></div></div><div class="metric-bars">${[["Lineup",a.lineupN],["Depth",a.depthN],["Dynasty",a.dynastyN],["Prod.",a.productionN],["Picks",a.capitalN]].map(x=>`<div class="mini-metric"><span>${x[0]}</span><strong>${Math.round(x[1])}</strong><i><b style="width:${Math.round(x[1])}%"></b></i></div>`).join("")}</div><div class="score-orb"><div><strong>${a.power.toFixed(1)}</strong><small>POWER</small></div></div></article>`).join("")}
function renderTeams(){const lid=String(state.currentLeague.league_id);$("teamsGrid").innerHTML=state.analytics.map(a=>{const m=state.managerMap.get(`${lid}:${a.rid}`),gm=state.managerGrades.find(x=>x.rid===a.rid);return `<article class="card team-card"><div class="team-line">${avatarHTML(lid,a.rid)}<div><strong>${esc(m?.teamName)}</strong><p>${esc(m?.displayName)}</p></div></div><div class="team-stats"><div><strong>#${a.rank}</strong><span>power</span></div><div><strong>${a.power.toFixed(1)}</strong><span>score</span></div><div><strong>${gm?.gmGrade||"—"}</strong><span>GM grade</span></div></div><div class="manager-insight">${esc(insight(gm||a))}</div></article>`}).join("")}
function renderManagers(){const lid=String(state.currentLeague.league_id);$("managerGrades").innerHTML=state.managerGrades.map(m=>`<article class="card manager-card"><div class="manager-head"><div class="team-line">${avatarHTML(lid,m.rid)}<div><strong>#${m.gmRank} ${esc(m.name)}</strong><br><small class="muted">Power rank #${m.rank} · ${m.tradeCount} trades</small></div></div><div class="manager-score-wrap"><small>GM SCORE</small><strong>${m.gmScore.toFixed(1)}</strong><span class="grade-pill ${gradeClass(m.gmGrade)}">${m.gmGrade}</span></div></div><div class="manager-components">${[["Power",m.power],["Trades",m.tradeScore],["Drafts",m.draftScore],["Results",m.results],["Assets",m.activity]].map(x=>`<div class="component"><span>${x[0]}</span><strong>${Math.round(x[1])}</strong><i><b style="width:${Math.round(x[1])}%"></b></i></div>`).join("")}</div><div class="manager-insight">${esc(insight(m))}</div></article>`).join("")}
function award(icon,title,m,detail){return `<article class="card award-card"><div class="award-shine"></div><div class="award-icon">${icon}</div><div class="award-title">${esc(title)}</div><div class="award-winner">${esc(m?.name||"—")}</div><div class="award-detail">${esc(detail)}</div></article>`}
function renderAwards(){const a=state.analytics,gm=state.managerGrades,trade=[...gm].sort((x,y)=>y.tradeScore-x.tradeScore)[0],draft=[...gm].sort((x,y)=>y.draftScore-x.draftScore)[0],young=[...a].sort((x,y)=>y.youth-x.youth)[0],deep=[...a].sort((x,y)=>y.depthN-x.depthN)[0],picks=[...a].sort((x,y)=>y.capitalN-x.capitalN)[0],active=[...gm].sort((x,y)=>y.tradeCount-x.tradeCount)[0],results=[...gm].sort((x,y)=>y.life.pct-x.life.pct)[0];$("awardsGrid").innerHTML=[award("🥩","GM of the Year",gm[0],`${gm[0]?.gmScore.toFixed(1)} GM score · ${gm[0]?.gmGrade}`),award("👑","Powerhouse",a[0],`${a[0]?.power.toFixed(1)} power score · ${a[0]?.tier}`),award("🤝","Trade Butcher",trade,`${trade?.tradeScore.toFixed(1)} average trade score`),award("🎯","Draft Day Butcher",draft,`${draft?.draftScore.toFixed(1)} draft score`),award("🐮","Best Young Core",young,`${young?.avgAge.toFixed(1)} average age among core players`),award("🏋️","Deepest Roster",deep,`${Math.round(deep?.depthN||0)} league-normalized depth`),award("🧾","War Chest",picks,`${Math.round(picks?.capital||0)} future pick value`),award("🔁","Trade Addict",active,`${active?.tradeCount||0} historical completed trades`),award("🏆","Legacy Leader",results,`${Math.round((results?.life.pct||0)*100)}% historical win rate`)].join("")}
function renderHome(){const ids=currentRosterIds(),bestGM=state.managerGrades[0],bestPower=state.analytics[0],bestDraft=[...state.managerGrades].sort((a,b)=>b.draftScore-a.draftScore)[0];$("homeLeaders").innerHTML=[[ "POWER LEADER",bestPower,`${bestPower?.power.toFixed(1)} power score`],["DYNASTY GM LEADER",bestGM,`${bestGM?.gmGrade} · ${bestGM?.gmScore.toFixed(1)}`],["DRAFT LEADER",bestDraft,`${bestDraft?.draftScore.toFixed(1)} draft score`]].map(x=>`<article class="card leader-card"><div class="leader-label">${x[0]}</div><div class="leader-name">${esc(x[1]?.name||"—")}</div><div class="leader-score">${esc(x[2])}</div></article>`).join("");$("homeStats").innerHTML=[["Seasons analyzed",state.seasons.length],["Completed trades",state.trades.length],["Draft classes",state.drafts.length],["NFL data",state.dataStatus.projections?"Stats + projections":"Historical stats"]].map(x=>`<div class="summary-card"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join("");$("homePower").innerHTML=state.analytics.slice(0,5).map(a=>`<div class="compact-row"><div class="rank-left"><span class="rank-num">${a.rank}</span>${avatarHTML(String(state.currentLeague.league_id),a.rid)}<div><strong>${esc(a.name)}</strong><br><small>${a.tier}</small></div></div><strong>${a.power.toFixed(1)}</strong></div>`).join("");$("recentTrades").innerHTML=state.trades.slice(0,5).map(t=>{const gs=state.tradeGrades.get(String(t.transaction_id))||[];return `<div class="compact-row"><div><strong>${esc((t.roster_ids||[]).map(r=>teamName(t._leagueId,r)).join(" ↔ "))}</strong><br><small>${esc(fmtDate(t.created))}</small></div><small>${gs.map(g=>g.grade).join(" / ")}</small></div>`}).join("")||'<div class="empty">No trades yet.</div>'}
function renderTrending(){for(const [type,id] of [["add","trendingAdds"],["drop","trendingDrops"]])api(`/players/nfl/trending/${type}?lookback_hours=24&limit=25`).then(rows=>{$(id).innerHTML=rows.map((x,i)=>`<div class="rank-row"><div class="rank-left"><span class="rank-num">${i+1}</span><div><strong>${esc(playerName(x.player_id))}</strong><br><small>${esc(playerPos(x.player_id))}</small></div></div><strong>${x.count}</strong></div>`).join("")}).catch(()=>$(id).innerHTML='<div class="empty">Trending data unavailable.</div>')}

function renderDrafts(){$("draftCountBadge").textContent=`${state.drafts.length} drafts`;const classes=[...new Set(state.drafts.map(d=>String(d.season)))];$("draftSummary").innerHTML=[["Classes",classes.length],["Picks graded",sum(state.drafts.map(d=>d.picks.length))],["Best GM draft score",state.managerGrades.length?Math.max(...state.managerGrades.map(x=>x.draftScore)).toFixed(1):"—"]].map(x=>`<div class="summary-card"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join("");$("draftsList").innerHTML=state.drafts.length?state.drafts.map(x=>{const tgs=state.draftGrades.filter(g=>g.draft.draft.draft_id===x.draft.draft_id);const pickGrade=new Map();tgs.forEach(t=>t.picks.forEach(pp=>pickGrade.set(String(pp.p.pick_no),pp.g)));return `<article class="draft-card"><div class="section-title-row"><div><p class="eyebrow">${esc(x.season)}</p><h3>${esc(x.draft.metadata?.name||x.draft.type||"Rookie Draft")}</h3></div><span class="badge">${x.picks.length} picks</span></div><div class="draft-team-grades">${tgs.sort((a,b)=>b.score-a.score).map(g=>`<div class="draft-team-grade"><strong>${esc(teamName(x.leagueId,g.rid))}</strong><span class="${gradeClass(g.grade)}">${g.grade}</span></div>`).join("")}</div><div class="draft-picks">${x.picks.slice(0,48).map(p=>{const g=pickGrade.get(String(p.pick_no));return `<div class="draft-pick">${g?`<span class="pick-grade ${gradeClass(g)}">${g}</span>`:""}<strong>${esc(p.pick_no)}. ${esc(p.metadata?.first_name&&p.metadata?.last_name?`${p.metadata.first_name} ${p.metadata.last_name}`:playerName(p.player_id))}</strong><span>${esc(teamName(x.leagueId,p.roster_id))}</span></div>`}).join("")}</div></article>`}).join(""):'<div class="card empty">No draft history found.</div>'}

function populateControls(){$("treeTeamSelect").innerHTML=currentRosterIds().map(r=>`<option value="${r}">${esc(teamName(String(state.currentLeague.league_id),r))}</option>`).join("");$("seasonFilter").innerHTML='<option value="all">All seasons</option>'+state.seasons.map(s=>`<option value="${s}">${s}</option>`).join("");populateRootTrades()}
function populateRootTrades(){const rid=Number($("treeTeamSelect").value),ts=tradesForCurrentRoster(rid);$("rootTradeSelect").innerHTML=ts.map(t=>{const h=resolveHistoricRosterForCurrent(rid,t),rec=assetsReceived(t,h).map(a=>a.label).slice(0,2).join(", ");return `<option value="${t.transaction_id}">${esc(t._season)} · ${esc(fmtDate(t.created))} · ${esc(rec||"Trade")}</option>`}).join("");renderTree()}
function findNextSpend(key,after,rid){for(const tx of [...state.trades].sort((a,b)=>Number(a.created)-Number(b.created))){if(Number(tx.created)<=Number(after))continue;const h=resolveHistoricRosterForCurrent(rid,tx);if(assetsSent(tx,h).some(a=>a.key===key))return{tx,rid:h}}return null}
function traceAsset(a,root,rid,d=0,v=new Set()){const k=`${a.key}:${root.transaction_id}`;if(v.has(k)||d>8)return null;v.add(k);const s=findNextSpend(a.key,root.created,rid);if(!s)return{asset:a,status:"held",depth:d,children:[]};return{asset:a,status:"spent",depth:d,spentTx:s.tx,children:assetsReceived(s.tx,s.rid).map(x=>traceAsset(x,s.tx,rid,d+1,new Set(v))).filter(Boolean)}}
function countNodes(n){return 1+(n.children||[]).reduce((a,c)=>a+countNodes(c),0)}function maxDepth(n){return Math.max(n.depth,...(n.children||[]).map(maxDepth))}
function nodeHTML(n){return `<div class="tree-level"><div class="tree-trade"><strong>${n.status==="held"?"Still held":"Moved again"}</strong><div class="tree-meta">${n.spentTx?`${esc(n.spentTx._season)} · ${esc(fmtDate(n.spentTx.created))}`:"Current branch endpoint"}</div></div><div class="tree-assets"><div class="asset ${n.status==="held"?"live":"spent"}"><span class="asset-type">${esc(n.asset.type)}</span><strong>${esc(n.asset.label)}</strong><small>${n.status==="held"?"Branch remains open":"Traded away"}</small>${n.children?.length?`<div class="tree-return">Became ${n.children.length} asset${n.children.length===1?"":"s"}</div>`:""}</div>${(n.children||[]).map(nodeHTML).join("")}</div></div>`}
function renderTree(){const rid=Number($("treeTeamSelect").value),tx=state.trades.find(t=>String(t.transaction_id)===String($("rootTradeSelect").value));if(!tx){$("treeCanvas").innerHTML='<div class="empty">No trade selected.</div>';return}const h=resolveHistoricRosterForCurrent(rid,tx),roots=assetsReceived(tx,h).map(a=>traceAsset(a,tx,rid)).filter(Boolean),nodes=roots.reduce((a,n)=>a+countNodes(n),0),open=roots.reduce((a,n)=>a+(JSON.stringify(n).match(/"status":"held"/g)||[]).length,0);$("branchCount").textContent=roots.length;$("treeTitle").textContent=`${teamName(tx._leagueId,h)} trade tree`;$("treeDate").textContent=fmtDate(tx.created);$("treeSummary").innerHTML=[["Starting assets",roots.length],["Total nodes",nodes],["Open endpoints",open]].map(x=>`<div class="summary-card"><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join("");$("treeCanvas").innerHTML=roots.length?roots.map(nodeHTML).join(""):'<div class="empty">No received assets could be mapped for this trade.</div>'}

function nav(view){document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===`view-${view}`));document.querySelectorAll(".tab").forEach(t=>t.classList.toggle("active",t.dataset.view===view));window.scrollTo({top:0,behavior:"smooth"})}
function bind(){document.querySelectorAll("[data-view]").forEach(x=>x.addEventListener("click",()=>nav(x.dataset.view)));document.querySelectorAll("[data-nav]").forEach(x=>x.addEventListener("click",()=>nav(x.dataset.nav)));$("refreshBtn").addEventListener("click",()=>location.reload());$("tradeSearch").addEventListener("input",renderTrades);$("seasonFilter").addEventListener("change",renderTrades);$("treeTeamSelect").addEventListener("change",populateRootTrades);$("rootTradeSelect").addEventListener("change",renderTree)}
async function init(){try{$("leagueIdLabel").textContent=LEAGUE_ID;$("footerLeague").textContent=LEAGUE_ID;await loadLeagueChain();$("leagueName").textContent=state.currentLeague.name||"All-Beef Dynasty";$("syncText").textContent="Loading league history…";await Promise.all([loadPeople(),loadTrades(),loadPlayers(),loadCurrentExtras()]);$("syncText").textContent="Loading NFL data…";await Promise.all([loadNFLData(),loadDrafts()]);buildAnalytics();buildTradeGrades();buildDraftGrades();buildManagerGrades();populateControls();renderHome();renderPower();renderTeams();renderTrades();renderDrafts();renderManagers();renderAwards();renderTrending();$("tradesBadge").textContent=`${state.trades.length} trades`;$("teamsBadge").textContent=`${currentRosterIds().length} teams`;$("syncText").textContent=`Synced · ${state.currentLeague.season}`;$("dataSourceFooter").textContent=`Sleeper league + ${state.dataStatus.projections?"NFL projections + ":""}historical fantasy stats`;bind()}catch(e){console.error(e);$("syncText").textContent="Sync failed";toast(e.message||"Unable to load league")}}
init();
})();